### ISSUE TITLE
attrs aren't getting bound to CdrInput

### ISSUE THREAD

**Issue by zcrumbo** [rei/rei-cedar#119]
Repro steps:

See https://codesandbox.io/s/cedarexamplesandbox-forked-i0bi12?file=/App.vue
`value` attr is getting bound to a number, but that value is not getting set on the input.

It seems like the `v-bind` directive doesn't get respected for native elements?
https://github.com/rei/rei-cedar/blob/main/src/components/input/CdrInput.vue#L234

**Comment by KenjiCrosland** [comment]
In the vue 3 version of cedar we're using `v-model` with `refs`

Check out the example here: https://codesandbox.io/s/cedarexamplesandbox-forked-mug4h1?file=/App.vue

You also no longer need to reference `this`
